### ISSUE TITLE
Pocketbook EPUB viewer 3 crash

### ISSUE THREAD

**Issue by TylerLaBree** [agrmohit/omnivore-epub#8] opened 2024-03-12 14:32 UTC
When I access certain parts of the omnivore epub using the default pocketbook viewer (3), the viewer crashes. I can mitigate this crash by opening it in the epub 2 viewer. I'm on a pocketbook era with software U700.6.8.2911

Steps to reproduce crash:

1. Add [this article](https://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/) to your omnivore library.
2. Make and move epub to pocketbook era.
3. Attempt to view that section of the epub.

Maybe there's something corrupted in the epub in that section, or maybe the pocketbook reader has a bug.

If you need someone with the device to test a fix, I'd be happy to help!

**Comment by agrmohit** [comment] 2024-03-12 16:03
Thanks for reporting the issue.

I am unable to reproduce this on my 11th gen Kindle Basic and am able to read the article without issues.

The most likely cause I can come up with is pocketbook having trouble displaying long, unsplit chapters. To confirm whether this is the case, can you try to load some huge article and see if it works. Something like [Gulliver’s Travels | Project Gutenberg](https://www.gutenberg.org/cache/epub/829/pg829-images.html) should do.

In the article you linked, there is a dead link to an image. There is a chance pocketbook crashes because it's trying to render a non-existent image. To test this, can you set `allowImages` in the config to `false` and try again.

My kindle handles both cases without issues so I am unable to test it further.

**Comment by TylerLaBree** [comment] 2024-03-12 17:23
Gulliver's Travels works. In addition, turning off images seemed to help, but when I turned on images again, the entire file works somehow.

There's a chance that I was running into a PocketBook issue. The device doesn't seem to enjoy me updating books that I've already opened on the device. Even after pushing an updated epub to the tablet, the tablet shows the old version of the epub. The Pocketbook is caching my epubs. Maybe things get corrupted when the cached version doesn't match the one in files.

More info:

The tablet makes a cached copy of epubs which have been opened in `/system/state/optimize/`. Deleting the specific file's cache when I update the epub seems to fix all issues I've been having. This could be a useful tip to include in the readme, if it's in-scope for the project to include advice like this.

**Comment by TylerLaBree** [comment] 2024-03-12 17:45
Update:

On some versions of the file, it still crashes. I haven't gotten a crash with images turned off, but also, crashes have occurred on pages without images. I'll see if I can troubleshoot this problem any further.

If the issue turns out to be bad image links, do you think it would be possible to remove those when making the epub?

**Comment by sascharucks** [comment] 2024-03-13 14:31
Maybe you could open a support ticket with Pocketbook as well? I think their reader shouldn't crash. Hopefully they can fix it.

I use Koreader on my Pocketbook. I can highly recommend it in general and did not have any problems on my Pocketbook with epub files created from this script.

**Comment by agrmohit** [comment] 2024-03-14 15:55
@TylerLaBree The library I am using to generate epub files ([epub-gen-memory](https://github.com/cpiber/epub-gen-memory)) does have an option to throw an error for bad image links. But I have set it to ignore errors because too many articles have dead links and it didn't seem like a good idea to terminate the program because a certain link is unreachable. The relevant section is below. But it doesn't seem to have an option to detect and selectively remove bad links.

```diff
diff --git a/main.ts b/main.ts
index f1c1500..e88b79d 100644
--- a/main.ts
+++ b/main.ts
@@ -198,7 +198,7 @@ async function makeEbook() {
       author: config.author,
       cover: config.cover,
       description: config.description,
-      ignoreFailedDownloads: true,
+      ignoreFailedDownloads: false,
     },
     chapters,
   );
```

Including details about PocketBook internals does seem fairly out of scope, but I am not opposed to including it if it seems to be a recurring issue.

I agree with @sascharucks that reporting it to PocketBook might be the best option here.

I too would use koreader on my Kindle if amazon was not determined to make it more locked down than iphones 😞.

**Comment by agrmohit** [comment] 2024-03-30 19:00
Closing this issue since there haven't been any more reports for this.

**Closed by agrmohit** 2024-03-30 19:00 UTC
Labels: bug, device-issue
